### ISSUE TITLE
"Back to top" button renders below other elements

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#106]
**Before**

![](http://i.venner.io/chrome_2018-08-02_16-21-14.png)

**After**

```css
.gmodstore-top {
    z-index: 999;
}
```

![](http://i.venner.io/chrome_2018-08-02_16-21-47.png)

Although, this hides other content. Would consider making the button transparent.
