### ISSUE TITLE
CSS Changes

### ISSUE THREAD

**Issue by kanalumaddela** [gmodstore/gmodstore-issues#257]
non important, low priority bois
actual css changes will come once the site's back up

1. featured addons
    - align discount/price with header at the middle or bottom
    - dark underlay so it looks fine across all images

```css
/* remove padding on header */
.big-spots .big-spot-title {
    padding-bottom: unset;
}
/* add padding to discount/price */
.big-spots .big-spot-text-right {
    padding-bottom: 5px;
}
/* dark underlay with the current html structure */
.big-spots .big-spot:before {
    content: '';
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 70px;
    background-color: rgba(0, 0, 0, 0.3);
}
```
![](https://i.mdd.la/chrome_2018-09-16_19-45-19.png)

2. addon/team stats on addon listing
    - debatable design

```css
/* marketplace - addon/teams*/
.big-header .left-text .addons span.big-text, .big-header .left-text .authors span.big-text {
    color: unset;
}
/* remove bg on addon/team # */
.big-header .left-text span.badge.badge-dark {
    position: relative;
    background: none;
}
.big-header .left-text span.badge.badge-dark:before {
    content: '';
    position: absolute;
    top: 0;
    right: -7px;
    width: 4px;
    height: 100%;
    background-color: #3097d1;
    transform: rotate(15deg);
}
```
![](https://i.mdd.la/chrome_2018-09-16_19-48-28.png)

3. background pattern
    - using heropatterns

```css
/* index bg pattern */
.index-header-bg {
    background-color: #3097d1;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='15' height='15' viewBox='0 0 8 8'%3E%3Cg fill='%232b88bd' fill-opacity='0.75'%3E%3Cpath fill-rule='evenodd' d='M0 0h4v4H0V0zm4 4h4v4H4V4z'/%3E%3C/g%3E%3C/svg%3E");
}
```
![](https://i.mdd.la/chrome_2018-09-17_13-21-37.png)

3. rounded avatar on forum posts
    - `.community-post-avatar .avatar` is missing a border radius, that's all

4. mentions
    - add a `@` before the name
    - fix where the background is being set along with the border radius

```css
/* mentions */
mention {
    display: inline-block;
    padding: 1px 5px;
    border-radius: 3px;
    background-color: #5bc0de;
}
mention a {
    padding: unset;
    border-radius: unset;
    background-color: unset;
}
mention a::before {
    content: '@';
    margin-right: 1px;
}
```
![](https://i.mdd.la/chrome_2018-09-18_22-13-55.png)

5. rating bar/ratings
    - make rating bar's opacity .5 by default
    - ratings scale up on hover

```css
/* ratings */
.community-post-action--rate {
    opacity: .5;
}
.community-post-rating--clickable {
    transition: transform .15s ease;
}
.community-post-rating--clickable:hover {
    transform: scale(1.25);
}
```
![](https://i.mdd.la/chrome_2018-09-18_22-14-21.png)
![](https://i.mdd.la/chrome_2018-09-18_22-15-11.png)

6. script/job/etc listings
    - fix dumbass green gradient

```css
/* listings */
.item-listing:hover .item-listing__bottom__right__price {
    background: unset;
    background-color: #80ab00;
}
```
![](https://i.mdd.la/chrome_2018-09-18_22-16-22.png)

7. alignment shit
    - navbar avatar
    - listing price

```css
/* fix navbar avatar */
.navbar-btn-avatar, .navbar-btn-avatar:active, .navbar-btn-avatar:active:focus, .navbar-btn-avatar:focus, .navbar-btn-avatar:hover, .navbar-btn-avatar:hover:active {
    margin-top: 2px;
}

/* fix price */
.item-listing__bottom__right__discount, .item-listing__bottom__right__price {
	line-height: 25px;
}
```

8. fix icon buttons
    - consistent border-radius with the rest of the site

```css
/* unset button icon radius */
.btn--icon-only {
    border-radius: .25rem;
}
```

9. addon search
    - darker bg instead of white
    - fix border-radius
    - i wish i could fix that shitty width increase, too much dumb css to trace through

```css
/* addon search */
.selectize-control.single .selectize-input {
    background-color: rgba(0, 0, 0, 0.2);
    border-radius: .25em;
}
.selectize-input.items.not-full.focus.input-active {
    background-color: rgba(0, 0, 0, 0.25);
}
#navbar-search-selectized, #navbar-search-selectized::placeholder {
    color: #f5f5f5;
}
```
![](https://i.mdd.la/chrome_2018-09-21_15-58-17.png)

**Comment by Threebow** [comment]
```css
#gmodstore-app > div.alert.alert-danger:first-child {
    display: none;
}
```
