### ISSUE TITLE
New addon aspect ratio not aligned/scaled on mobile

### ISSUE THREAD

**Issue by Silhouhat** [gmodstore/gmodstore-issues#315]
![image](https://user-images.githubusercontent.com/20209805/45659377-1f848380-bac2-11e8-86a0-3b9a72951755.png)

**Comment by Silhouhat** [comment]
DarkRP City Worker is using the new aspect ratio, Achievements is not.

**Comment by WilliamVenner** [comment]
here is the fix x

```css
.item-listing__top {
    width: 100%;
}
```
