### ISSUE TITLE
Inconsistent script banner dimensions causing issues in grid layouts

### ISSUE THREAD

**Issue by WilliamVenner** [gmodstore/gmodstore-issues#402]
Example: https://www.gmodstore.com/help/tickets/create/addon

Fix:

```css
.item-listing__top {
    height: 120px;
    display: table;
    width: 100%;
}
.item-listing__top > div {
    position: relative;
    display: table-cell;
    vertical-align: middle;
    overflow: hidden;
    text-align: center;
}
.item-listing__top__img {
    max-height: 120px;
    max-width: 100%;
    width: auto;
}
.item-listing__top > div > .item-listing__background {
    position: absolute;
    width: calc(100% + 10px);
    height: calc(100% + 10px);
    background-size: cover;
    background-position: center center;
    -webkit-filter: blur(5px);
    filter: blur(5px);
    content: "";
    left: -5px;
    top: -5px;
    z-index: -1;
}
```

**Comment by kanalumaddela** [comment]
imo my fix is better as it doesn't stretch the banners to be bigger than their original size causing it to ***look*** blurry. I will give it to @WilliamVenner though, his css makes Nobody's banner look normal.

```css
.item-listing__top {
    width: 100%;
    text-align: center;
}
.item-listing__top__img {
    width: unset;
}
```

**before**
![](https://i.mdd.la/chrome_2018-09-23_22-52-33.png)

---

**billys**
![](https://i.mdd.la/chrome_2018-09-23_22-54-39.png)

---

**mine**
![](https://i.mdd.la/chrome_2018-09-23_22-53-03.png)

**Comment by WilliamVenner** [comment]
@kanalumaddela actually my fix worked fine, I just forgot to include `width: auto`

**Comment by kanalumaddela** [comment]
> @kanalumaddela actually my fix worked fine, I just forgot to include `width: auto` 😩

it breaks a user's addon page though like https://www.gmodstore.com/users/76561198135875727/addons

literally just copied pasted and commented my own css to double check
![](https://i.mdd.la/chrome_2018-09-24_13-40-57.png)

**Comment by WilliamVenner** [comment]
fixed again thank you :)

**Comment by kanalumaddela** [comment]
🤦 do you understand what your css is doing?

Currently, you are stretching the width of the new banners while **also** shrinking their height to match the old ones, so each individual card has the same dimensions. That doesn't look good whatsoever as your banner goes from
![](https://i.mdd.la/chrome_2018-09-24_16-31-51.png)
to
![](https://i.mdd.la/chrome_2018-09-24_16-32-47.png)

there's a reason i suggested my fix because it maintains their aspect ratio

![](https://i.mdd.la/chrome_2018-09-24_16-34-19.png)

**Comment by WilliamVenner** [comment]
yes I actually do kanal, thanks for webshitsplaining CSS to me. t'was was simply a mistake in the editing of the issue, sorry for the inconvenience this has caused to your menopause

**Comment by DiablosCorp** [comment]
I don't read your bullshit but just to tell you that it happens on phone on the new banners
![screenshot_20180925-101404_chrome](https://user-images.githubusercontent.com/42046569/46001713-44718b80-c0ac-11e8-89c9-05946cca2f14.jpg)

**Comment by WilliamVenner** [comment]
Why doesn't GmodStore support IE 9 😠😠😠

**Comment by WilliamVenner** [comment]
ooh, well if we're using a modern approach using flexbox rather than table `vertical-align`, we don't need `.item-listing__top > div` anymore.

If you remove `.item-listing__top > div`, then this CSS will work:

```css
.item-listing__top__img {
	max-height: 120px;
	max-width: 100%;
	width: auto;
}
.item-listing__top {
	height: 120px;
	display: flex;
	justify-content: center;
	align-items: center;
	position: relative;
	overflow: hidden;
}
.item-listing__top > .item-listing__background {
	position: absolute;
	width: calc(100% + 10px);
	height: calc(100% + 10px);
	background-size: cover;
	-webkit-filter: blur(5px);
	filter: blur(5px);
	content: "";
	left: -5px;
	top: -5px;
	z-index: -1;
}
```

**JavaScript for testing this**
```js
var css = `
.item-listing__top__img {
	max-height: 120px;
	max-width: 100%;
	width: auto;
}
.item-listing__top {
	height: 120px;
	display: flex;
	justify-content: center;
	align-items: center;
	position: relative;
	overflow: hidden;
}
.item-listing__top > .item-listing__background {
	position: absolute;
	width: calc(100% + 10px);
	height: calc(100% + 10px);
	background-size: cover;
	-webkit-filter: blur(5px);
	filter: blur(5px);
	content: "";
	left: -5px;
	top: -5px;
	z-index: -1;
}
`;

$(document.createElement("style")).html(css).appendTo("head"); // inject our CSS
$(".item-listing__top").each(function() {
	$(this).html($(this).find(">div").html()); // unwrap content in .item-listing__top > div
});
```
